### ISSUE TITLE
Force update, limiting being able to close the update screen

### ISSUE THREAD

**Issue by hortigado** [TrangLeQuynh/flutter-upgrade-version#26]
Hello, great work, I have a question according to the description AppUpdateType.immediate is used to force the update but the user can close this window. How can we prevent this alert from closing, which in my opinion should not have the close button on this type or should a variable be implemented to disable the button.
![image](https://github.com/TrangLeQuynh/flutter-upgrade-version/assets/42924254/3655e142-47b5-411d-bf98-6081b59cb922)

**Comment by TrangLeQuynh** [comment]
Hello, @hortigado Thank you for your feedback.  I've also thought like it. But I'm using the Play In-App Update package, Google Play will handle the update installation. Therefore I cannot edit this default dialog details. 

I think that you should not force users to update the app. Forcing updates to users is considered a very bad user experience. 

_**Note**: Be mindful of how often you request updates to avoid annoying or tiring your users. You should only request in-app updates for changes that are important to the core functionality of your app._

**Comment by hortigado** [comment]
@TrangLeQuynh Thanks, I was thinking of changing the backend endpoint of my app and therefore in older versions it would stop working. I will see a way to introduce this change without forcing an update. Thank you
