### ISSUE TITLE
With gradle 8 not working

### ISSUE THREAD

**Issue by TheHypnoo** [TrangLeQuynh/flutter-upgrade-version#32]
Hello, first of all a good job on this plugin.

It seems that Gradle 8 does not work with the plugin. 

You should add the namespace so that it could work.

> A problem occurred configuring project ':flutter_upgrade_version'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

PR: #33

**Comment by TrangLeQuynh** [comment]
Hello @TheHypnoo, thank you for your pull request.  AGP 8.0 requires to specify a **namespace** in the module's build file. But This didn't work with < AGP 4.2. 
I have 2 comments on your request. Please check your pull request again.

**Comment by TrangLeQuynh** [comment]
@TheHypnoo I have published a new version (**1.1.3**) to fix this issue.
>> Android: Adds a namespace for compatibility with AGP 8.0

**Comment by TheHypnoo** [comment]
Thanks.
