### ISSUE TITLE
Tutorial Video

### ISSUE THREAD

**Issue by emre86t** [TrangLeQuynh/flutter-upgrade-version#35]
The plugin is really well thought out and the fact that it has the ability to show warnings on the iOS side compared to similar ones makes the plugin a reason for preference.
This plugin needs to reach more people. I think those who code Flutter should be aware of this plugin.
Here is my suggestion:
Please reach out to Youtubers who give Flutter lessons and make tutorial videos explaining this plugin.
Thank you for your efforts and sweat.

**Comment by TrangLeQuynh** [comment]
@emre86t Thank you for your suggestion. I also thought about your suggestion before. I'm still a little shy about making tutorial videos on YouTube. I will try to make it as soon as possible.
