### ISSUE TITLE
Error in AppUpdateService

### ISSUE THREAD

**Issue by demanhamed** [TrangLeQuynh/flutter-upgrade-version#46]
I encountered an error related to the AppUpdateService in my  app. The error message is as follows:
`I/flutter ( 8845): ERROR : MSG_UPDATE_INFO_TASK_EXCEPTION`

Steps to Reproduce:

Launch the app.
Observe the error message in the logs.
Expected Behavior: The AppUpdateService should function without errors.

Full logs:
`
I/PlayCore( 8845): UID: [10337]  PID: [8845] AppUpdateService : requestUpdateInfo(app.ajbarly)
I/PlayCore( 8845): UID: [10337]  PID: [8845] AppUpdateService : Initiate binding to the service.
I/PlayCore( 8845): UID: [10337]  PID: [8845] AppUpdateService : ServiceConnectionImpl.onServiceConnected(ComponentInfo{com.android.vending/com.google.android.finsky.installservice.DevTriggeredUpdateService})
I/PlayCore( 8845): UID: [10337]  PID: [8845] AppUpdateService : linkToDeath
I/PlayCore( 8845): UID: [10337]  PID: [8845] AppUpdateService : Unbind from service.
I/PlayCore( 8845): UID: [10337]  PID: [8845] OnRequestInstallCallback : onRequestInfo
I/flutter ( 8845): ERROR : MSG_UPDATE_INFO_TASK_EXCEPTION
`

**Comment by TrangLeQuynh** [comment]
Is your app released yet? Or Have you used internal testing to test it?

**Comment by demanhamed** [comment]
It’s currently in closed testing. Does it only work with apps that are already in production?

**Comment by TrangLeQuynh** [comment]
You can use internal test in google play console. [How to test In-App Update](https://medium.com/@tranglequynh710/how-to-test-in-app-update-in-android-be48562d445d)

**Comment by demanhamed** [comment]
I see... which means it doesn't work with closed testing
